### ISSUE TITLE
レストランと料理のサンプル画像、計40枚用意

### ISSUE THREAD

**Issue by machida** [hayasaki-shunsuke/kagomeshi#10]
app/assets/images/samples/restaurants の中に、

restaurant_1.png、restaurant_2.png、restaurant_3.png ... と番号を振って入れる。

この辺から探す

- https://www.pakutaso.com/
- https://pixabay.com/ja/

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56114566-32016580-5f9c-11e9-8de3-c27ad2adc645.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56114680-87d60d80-5f9c-11e9-9fb2-896a604f4c4c.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56116822-b99da300-5fa1-11e9-8cf3-c9d28f4de4e6.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56131730-3725db00-5fc3-11e9-8ae5-e0ae267023d2.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56131783-61779880-5fc3-11e9-8532-4384288ead12.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56131860-997edb80-5fc3-11e9-99dc-80c4dff6165d.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56131902-ad2a4200-5fc3-11e9-9c7d-5eea569101dc.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56131944-c7642000-5fc3-11e9-8871-ba8fbb531a54.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56131969-d519a580-5fc3-11e9-9a5e-b2e291d0bd25.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132043-fb3f4580-5fc3-11e9-9802-3cceffa47ec5.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132071-085c3480-5fc4-11e9-80c2-7e17f87af501.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132132-2a55b700-5fc4-11e9-912f-ac8ffb647682.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132192-52ddb100-5fc4-11e9-8c2c-9278fc76065f.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132283-8ddfe480-5fc4-11e9-9a7b-9f977bb31ff1.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132329-a7812c00-5fc4-11e9-9206-10db26906661.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132355-b7990b80-5fc4-11e9-873b-c0c83171985c.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132377-c54e9100-5fc4-11e9-9b82-a7606c3b8059.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132405-d6979d80-5fc4-11e9-8d75-1f058a90f84c.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132434-e911d700-5fc4-11e9-92f6-e8abc8a137e9.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132463-fcbd3d80-5fc4-11e9-8179-d60dab6c0fa6.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132498-13fc2b00-5fc5-11e9-9f70-f0cff22edf06.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132531-2bd3af00-5fc5-11e9-8908-b2b2bd663f6f.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132600-5f163e00-5fc5-11e9-8249-d3c0d3a25813.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132657-82d98400-5fc5-11e9-9ea9-66aad29eadda.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132701-a56b9d00-5fc5-11e9-9969-97522474028e.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132772-d8159580-5fc5-11e9-8f18-bf2bbd4300b0.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132823-ec599280-5fc5-11e9-9f05-b3f7247499ef.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132864-0b582480-5fc6-11e9-860f-794075e80976.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132888-25920280-5fc6-11e9-968a-83bf1f79fd65.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132936-422e3a80-5fc6-11e9-9138-557c38fee786.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56132997-612ccc80-5fc6-11e9-8e64-3f30e85d565a.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133040-7a357d80-5fc6-11e9-8613-1ac9df840a87.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133106-a224e100-5fc6-11e9-9daa-edec96a2837b.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133136-b072fd00-5fc6-11e9-97e1-52d44399f9de.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133152-bbc62880-5fc6-11e9-8943-fec2f65ac624.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133200-d3051600-5fc6-11e9-8461-115ac663656a.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133242-e87a4000-5fc6-11e9-84da-c48fcc73f7ec.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133499-83731a00-5fc7-11e9-805b-0c59d61e66de.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133545-a4d40600-5fc7-11e9-997b-d9880592c276.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133617-c7feb580-5fc7-11e9-86f2-bc53ce389005.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133634-d220b400-5fc7-11e9-83fc-ccdf4e1fc5d3.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133663-e8c70b00-5fc7-11e9-951a-7c1ad036e743.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133726-1c099a00-5fc8-11e9-974d-da08612c5f4c.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133833-4e1afc00-5fc8-11e9-8d5b-3e4b90ba430b.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133875-64c15300-5fc8-11e9-80ce-031b7d298c96.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133907-70147e80-5fc8-11e9-9dc3-8f0c2c6e82bb.png)

**Comment by machida** [comment]
![image](https://user-images.githubusercontent.com/168265/56133929-7a367d00-5fc8-11e9-8d97-75d570332357.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56196560-0355be80-6072-11e9-9163-58de78ab12f8.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56196646-35672080-6072-11e9-81ca-7c718457acbd.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56196770-6f382700-6072-11e9-9abd-ba27b6c5bb0e.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56196794-7fe89d00-6072-11e9-906d-3ae04fbdf700.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56197339-980cec00-6073-11e9-9360-39be29237fdb.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56277396-39ad3f80-613f-11e9-9106-df17cfb54d51.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56734488-f3d72380-679d-11e9-8c85-6a1bc8153a3d.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56734546-179a6980-679e-11e9-9e8f-fc410b638276.png)

**Comment by HouraiSyuto** [comment]
![image](https://user-images.githubusercontent.com/48552047/56734579-3993ec00-679e-11e9-80bd-1cfa15e7b13a.png)
