### ISSUE TITLE
画像のデータがエラーになっている

### ISSUE THREAD

**Issue by HouraiSyuto** [hayasaki-shunsuke/kagomeshi#61]
画像のデータがエラーになっている原因は何か。
また、エラーを解決する。

![image](https://user-images.githubusercontent.com/48552047/67449802-5aa69e00-f656-11e9-9832-077b814658fe.png)

**Comment by hayasaki-shunsuke** [comment]
test

**Comment by hayasaki-shunsuke** [comment]
testtt

**Comment by hayasaki-shunsuke** [comment]
testing

**Comment by hayasaki-shunsuke** [comment]
tes
